// <auto-generated />
using System;
using ELNETFINALPROJECT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELNETFINALPROJECT.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510034951_AddStationTable")]
    partial class AddStationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ELNETFINALPROJECT.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentGame")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStation")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SessionHourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SessionStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPlaytimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ELNETFINALPROJECT.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentUser")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPoweredOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnavailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SessionStartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimePaidMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeUsedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPlayerId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("ELNETFINALPROJECT.Models.Station", b =>
                {
                    b.HasOne("ELNETFINALPROJECT.Models.Account", "CurrentPlayerAccount")
                        .WithMany()
                        .HasForeignKey("CurrentPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentPlayerAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
